config/routes.rb
TimesheetsApp::Application.routes.draw do
  resources :timesheets

  resources :projects

  resources :employees

  match 'new_timesheet/:id' =>  'timesheets#new'
  match 'show_timesheets/:id' => 'employees#alltimesheets'

  root :to => 'employees#index'

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  attr_accessible :email, :name
  has_many :timesheets
  has_many :projects, through: :timesheets  
  validates :name, :email, presence: true
  validates :email, uniqueness: true
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :desc, :name
  has_many :timesheets
  has_many :employees, through: :timesheets  
  validates :name, presence: true, uniqueness: true
end

app/models/timesheet.rb
class Timesheet < ActiveRecord::Base
  attr_accessible :approved, :employee_id, :project_id, :workdate, :workend, :workstart
  belongs_to :employee
  belongs_to :project  
  validates :employee_id, :project_id, presence: true
  validates :duration, numericality: {greater_than: 0 }
  validate :validate_dates

  def duration
    workend-workstart
  end 
  
  def duration_in_hrs
    duration.to_i/3600
  end 
  
  def validate_dates
     if self.workdate > Date.today
	   errors.add(:workdate, "Work date cannot be in future")
	 end 
  end 



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @employees }
    end
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
    @employee = Employee.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @employee }
    end
  end

  def alltimesheets
    @employee = Employee.find(params[:id])
  end

  # GET /employees/new
  # GET /employees/new.json
  def new
    @employee = Employee.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @employee }
    end
  end

  # GET /employees/1/edit
  def edit
    @employee = Employee.find(params[:id])
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(params[:employee])

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render json: @employee, status: :created, location: @employee }
      else
        format.html { render action: "new" }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /employees/1
  # PUT /employees/1.json
  def update
    @employee = Employee.find(params[:id])

    respond_to do |format|
      if @employee.update_attributes(params[:employee])
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy

    respond_to do |format|
      format.html { redirect_to employees_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/timesheets_controller.rb
class TimesheetsController < ApplicationController
  # GET /timesheets
  # GET /timesheets.json
  def index
    @timesheets = Timesheet.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @timesheets }
    end
  end

  # GET /timesheets/1
  # GET /timesheets/1.json
  def show
    @timesheet = Timesheet.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @timesheet }
    end
  end

  # GET /timesheets/new
  # GET /timesheets/new.json
  def new
    @employee = Employee.find(params[:id])
    @timesheet = Timesheet.new
    @timesheet.employee_id = @employee.id

    @projects_array = (Project.all.map{|project| [project.name, project.id]})

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @timesheet }
    end
  end

  # GET /timesheets/1/edit
  def edit
    @timesheet = Timesheet.find(params[:id])
  end

  # POST /timesheets
  # POST /timesheets.json
  def create
    p params
    @timesheet = Timesheet.new(params[:timesheet])
    @employee = Employee.find(@timesheet.employee_id)
    @projects_array = (Project.all.map{|project| [project.name, project.id]})

    respond_to do |format|
      if @timesheet.save
        format.html { redirect_to "/show_timesheets/#{@employee.id}", notice: 'Timesheet was successfully created.' }
        format.json { render json: @timesheet, status: :created, location: @timesheet }
      else
        format.html { render action: "new" }
        format.json { render json: @timesheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /timesheets/1
  # PUT /timesheets/1.json
  def update
    @timesheet = Timesheet.find(params[:id])

    respond_to do |format|
      if @timesheet.update_attributes(params[:timesheet])
        format.html { redirect_to @timesheet, notice: 'Timesheet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @timesheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /timesheets/1
  # DELETE /timesheets/1.json
  def destroy
    @timesheet = Timesheet.find(params[:id])
    @timesheet.destroy

    respond_to do |format|
      format.html { redirect_to timesheets_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/timesheets_helper.rb
module TimesheetsHelper
end

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employees/alltimesheets.html.erb
<h3 class="text-error">Timesheets of employee: <%= @employee.name %> (email: <%= @employee.email %>)</h3>

<div class="row-fluid"><div class="span4 offset1">
<% @employee.timesheets.group_by{|a| a.workdate.cweek}.each do |ww, timesheets| %>
<% total_hrs = 0%>
<h4 class="text-success">WW<%= ww%>:</h4>
<table class="table table-bordered table-condensed table-striped table-hover">
<tr>
  <th class="text-warning">PROJECT</th>
  <th class="text-warning">DATE</th>
  <th class="text-warning">DURATION</th>
</tr>
<% timesheets.sort{|a,b| a.workstart <=> b.workstart}.each do |timesheet| 
   total_hrs += timesheet.duration_in_hrs %>
<tr>
  <td><%= timesheet.project.name %></td>
  <td>WW<%= timesheet.workdate.cweek %>.<%= timesheet.workdate.cwday%></td>
  <td><%= timesheet.duration_in_hrs %> hrs</td>
</tr>
<% end %>
<tr>
  <td class="text-info">WW<%= ww%></td><td class="text-info">Total: </td><td class="text-info"><%= total_hrs%> hrs</td>
</tr>
</table>
<% end %>
</div>
</div>

<div class="row-fluid">
<div class="span6">

<a href="/new_timesheet/<%=@employee.id%>">New Timesheet</a>
</div>
</div>

app/views/employees/edit.html.erb
<h1>Editing employee</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<br />
<br />
<br />
<div class="row-fluid">
  <div class="span1"></div>
  <div class="span5">
   <table class="table table-bordered table-condensed table-hover table-striped span11">
   <tr>
     <th>Name</th>
     <th>Email</th>
     <th>New</th>
     <th>Show</th>
   </tr>
   <% @employees.each do |employee| %> 
      <tr>
         <td><%= link_to employee.name, employee %></td>
         <td><%= link_to employee.email, employee %></td>
         <td><btn class="btn btn-primary btn-info"><a href="/new_timesheet/<%=employee.id%>"><i class="icon-calendar icon-white"> </i></a></btn></td>
         <td><btn class="btn btn-primary btn-success"><a href="/show_timesheets/<%=employee.id%>"><i class="icon-list icon-white"> </i></a></btn></td>
      </tr> 
   <% end %> 
   </table>
   </div>
  <div class="span3"></div>
</div>

app/views/employees/new.html.erb
<h1>New employee</h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @employee.name %>
</p>

<p>
  <b>Email:</b>
  <%= @employee.email %>
</p>


<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TimesheetsApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-fixed-top">
   <div class="navbar-inner"> 
         <a class="brand" href="/" style="font-size: 27px; font-weight: bold; font-family: Tahoma,Serif;">&nbsp;&nbsp;&nbsp;COGNIZANT TIMESHEETS&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</a>
         <div class="nav-collapse collapse">
           <ul class="nav pull-right">
              <li><a href="/" title="Home" style="font-size: 20px;"><i class="icon-home icon-white"></i> Home</a></li>
              <li><a href="/projects" title="Projects" style="font-size: 20px;"><i class="icon-book icon-white"></i> Projects</a></li>
              <li><a href="/employees/new" title="New Employees" style="font-size: 20px;"><i class="icon-picture icon-white"></i> New Employee</a></li>
              <li class="dropdown">
                  <a class="dropdown-toggle" data-toggle="dropdown" style="font-size: 20px;"  href="#"><i class="icon-globe icon-white"></i> Admin<b class="caret"></b></span></a>
                  <ul class="dropdown-menu">
                      <li><%= link_to "New Employee", new_employee_path %></a></li>
                      <li><%= link_to "New Project", new_project_path %></a></li>
                  </ul>
              </li>
            </ul>
         </div>   
   </div>
  </div>
<br />
<%= yield %>

</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :desc %><br />
    <%= f.text_area :desc %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<div class="row-fluid">
  <div class="span4">
<h1 class="text-error">Projects</h1>

<table class="table table-condensed table-striped table-hover table-bordered span9">
  <tr>
    <th>Name</th>
    <th>Desc</th>
  </tr>

<% @projects.each do |project| %>
  <tr>
    <td><%= project.name %></td>
    <td><%= project.desc %></td>
  </tr>
<% end %>
</table>
</div>
<div>

<br />
<br />

<div class="row-fluid">
<div class="span 8">
<%= link_to 'New Project', new_project_path %>
</div></div>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @project.name %>
</p>

<p>
  <b>Desc:</b>
  <%= @project.desc %>
</p>


<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/timesheets/_form.html.erb
<%= form_for(@timesheet) do |f| %>
  <% if @timesheet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@timesheet.errors.count, "error") %> prohibited this timesheet from being saved:</h2>

      <ul>
      <% @timesheet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <input type="hidden" name="timesheet[employee_id]" value="<%=@employee.id%>"> 
  <div class="field">
    <%= f.label :project_id %><%= select(:timesheet, :project_id, @projects_array) %>
  </div>
  <div class="field">
    <%= f.label :workdate %><%= f.date_select :workdate %>
  </div>
  <div class="field">
    <%= f.label :workstart %><%= f.time_select :workstart %>
  </div>
  <div class="field">
    <%= f.label :workend %><%= f.time_select :workend %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/timesheets/edit.html.erb
<h1>Editing timesheet</h1>

<%= render 'form' %>

<%= link_to 'Show', @timesheet %> |
<%= link_to 'Back', timesheets_path %>

app/views/timesheets/index.html.erb
<h1>Listing timesheets</h1>

<table>
  <tr>
    <th>Employee</th>
    <th>Project</th>
    <th>Workdate</th>
    <th>Workstart</th>
    <th>Workend</th>
    <th>Approved</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @timesheets.each do |timesheet| %>
  <tr>
    <td><%= timesheet.employee_id %></td>
    <td><%= timesheet.project_id %></td>
    <td><%= timesheet.workdate %></td>
    <td><%= timesheet.workstart %></td>
    <td><%= timesheet.workend %></td>
    <td><%= timesheet.approved %></td>
    <td><%= link_to 'Show', timesheet %></td>
    <td><%= link_to 'Edit', edit_timesheet_path(timesheet) %></td>
    <td><%= link_to 'Destroy', timesheet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Timesheet', new_timesheet_path %>

app/views/timesheets/new.html.erb
<h3 class="text-success">Creating new timesheet for <%=@employee.name%></h3>
<br />
<div class="row-fluid">
<div class="span1"></div>
<div class="span10">
  <%= render 'form' %>
</div>
</div>
<%= link_to 'Back', root_path %>

app/views/timesheets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Employee:</b>
  <%= @timesheet.employee_id %>
</p>

<p>
  <b>Project:</b>
  <%= @timesheet.project_id %>
</p>

<p>
  <b>Workdate:</b>
  <%= @timesheet.workdate %>
</p>

<p>
  <b>Workstart:</b>
  <%= @timesheet.workstart %>
</p>

<p>
  <b>Workend:</b>
  <%= @timesheet.workend %>
</p>

<p>
  <b>Approved:</b>
  <%= @timesheet.approved %>
</p>


<%= link_to 'Edit', edit_timesheet_path(@timesheet) %> |
<%= link_to 'Back', timesheets_path %>